credentials_file = "credentials.json"
project_id       = "graphite-space-382215"
region           = "us-central1"
zone             = "us-central1-a"
image_name       = "debian-cloud/debian-11"
instance_type    = "n1-standard-1"
